# Generated by Django 5.2.7 on 2025-10-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='campaigns.recipient'),
        ),
    ]
